INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Animal Magnetism", "The Restless Ghost");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Animal Magnetism", "Ernest the Chicken");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Animal Magnetism", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Another Slice of H.A.M.", "Death to the Dorgeshuun");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Another Slice of H.A.M.", "The Giant Dwarf");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Another Slice of H.A.M.", "The Digsite");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Between a Rock...", "Dwarf Cannon");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Between a Rock...", "Fishing Contest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Biohazard", "Plague City");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Cabin Fever", "Pirate's Treasure");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Cabin Fever", "Rum Deal");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Contact!", "Prince Ali Rescue");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Contact!", "Gertrude's Cat");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Contact!", "Icthlarin's Little Helper");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Creature of Fenkenstrain", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Creature of Fenkenstrain", "The Restless Ghost");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Darkness of Hallowvale", "In Aid of the Myreque");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Death to the Dorgeshuun", "The Lost Tribe");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Desert Treasure", "Digsite Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Desert Treasure", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Desert Treasure", "Temple of Ikov");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Desert Treasure", "The Tourist Trap");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Desert Treasure", "Troll Stronghold");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Desert Treasure", "Waterfall Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Devious Minds", "Wanted!");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Devious Minds", "Troll Stringhold");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Devious Minds", "Recruitment Drive");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Devious Minds", "Doric's Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Dream Mentor", "Lunar Diplomacy");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Dream Mentor", "Eadgar's Ruse");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Eadgar's Ruse", "Druidic Ritual");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Eadgar's Ruse", "Troll Stronghold");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Elemental Workshop II", "Elemental Workshop I");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Eyes of Glouphrie", "The Grand Tree");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("FairyTale I - Growing Pains", "The Lost City");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("FairyTale I - Growing Pains", "Nature Spirit");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Fairytale II - Cure a Queen", "FairyTale I - Growing Pains");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Forgettable Tale of a Drunken Dwarf", "The Giant Dwarf");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Forgettable Tale of a Drunken Dwarf", "Fishing Contest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Fremennik Isles", "The Fremennik Trials");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Garden of Tranquillity", "Creature of Fenkenstrain");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Ghosts Ahoy", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Ghosts Ahoy", "The Restless Ghost");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Great Brain Robbery", "Creature of Fenkenstrain");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Great Brain Robbery", "Cabin Fever");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Great Brain Robbery", "Recipe for Disaster");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Grim Tales", "Witch's House");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Haunted Mine", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Heroes' Quest", "Shield of Arrav");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Heroes' Quest", "The Lost City");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Heroes' Quest", "Dragon Slayer");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Heroes' Quest", "Merlin's Crystal");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Holy Grail", "Merlin's Crystal");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Icthlarin's Little Helper", "Gertrude's Cat");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("In Aid of the Myreque", "In Search of te Myreque");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("In Aid of the Myreque", "Nature Spirit");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("In Search of the Myreque", "Nature Spirit");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Jungle Potion", "Druidic Ritual");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("King's Ransom", "Black Knight's Fortress");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("King's Ransom", "Merlin's Crystal");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("King's Ransom", "Holy Grail");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("King's Ransom", "Murder Mystery");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("King's Ransom", "One Small Favour");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Legends' Quest", "Family Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Legends' Quest", "Heroes Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Legends' Quest", "Shilo Village Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Legends' Quest", "Underground Pass");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Legends' Quest", "Waterfall Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Lost Tribe", "Goblin Diplomacy");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Lost Tribe", "Rune Mysteries");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Lunar Diplomacy", "Fremennik Trials");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Lunar Diplomacy", "The Lost City");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Lunar Diplomacy", "Rune Mysteries");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Lunar Diplomacy", "Shilo Village");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Making History", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Making History", "The Restless Ghost");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Monkey Madness", "The Grand Tree");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Monkey Madness", "Tree Gnome Village");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Monkey Madness II", "Enlightened Journey");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Monkey Madness II", "The Eyes of Glouphrie");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Monkey Madness II", "Recipe for Disaster");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Monkey Madness II", "Troll Stronghold");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Monkey Madness II", "Watchtower");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Mourning's End Part I", "Big Chompy Bird Hunting");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Mourning's End Part I", "Roving Elves");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Mourning's End Part I", "Sheep Herder");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Mourning's End Part II", "Mourning's End Part I");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("My Arm's Big Adventure", "Eadgar's Ruse");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("My Arm's Big Adventure", "The Fued");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("My Arm's Big Adventure", "Jungle Potion");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Nature Spirit", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Nature Spirit", "The Restless Ghost");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Olaf's Quest", "The Fremennik Trials");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("One Small Favour", "Druidic Ritual");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("One Small Favour", "Rune Mysteries");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("One Small Favour", "Shilo Village");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Rat Catchers", "Gertrude's Cat");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Rat Catchers", "Icthlarin's Little Helper");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Cook's Assistant");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Fishing Contest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Goblin Diplomacy");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Big Chompy Bird Hunting");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Murder Mystery");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Nature Spirit");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Witch's House");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Gertrude's Cat");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Shadow of the Storm");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Legends' Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Monkey Madness");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Desert Treasure");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recipe for Disaster", "Horror from the Deep");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recruitment Drive", "Black Knight's Fortress");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Recruitment Drive", "Druidic Ritual");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Regicide", "Underground Pass");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Roving Elves", "Regicide");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Roving Elves", "Waterfall Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Royal Trouble", "Throne of Miscellania");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Rum Deal", "Zogre Flesh Eaters");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Shades of Mort'ton", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Shadow of the Storm", "Demon Slayer");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Shadow of the Storm", "The Golem");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Shilo Village", "Jungle Potion");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Slug Menace", "Wanted!");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("The Slug Menace", "Sea Slug");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Swan Song", "One Small Favour");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Swan Song", "Garden of Tranquillity");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Tai Bwo Wannai Trio", "Jungle Potion");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("A Tail of Two Cats", "Gertrude's Cat");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("A Tail of Two Cats", "Icthlarin's Little Helper");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Throne of Miscellania", "Fremennik Trials");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Throne of Miscellania", "Heroes Quest");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Troll Romance", "Troll Stronghold");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Troll Romance", "Death Plateau");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Troll Stronghold", "Death Plateau");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Underground Pass", "Biohazard");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Wanted!", "The Lost Tribe");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Wanted!", "Priest in Peril");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Wanted!", "Recruitment Drive");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Wanted!", "Rune Mysteries");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("What Lies Below", "Rune Mysteries");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Zogre Flesh Eaters", "Big Chompy Bird Hunting");
INSERT INTO QuestPrerequisite(baseQuest, prerequisiteQuest) VALUES("Zogre Flesh Eaters", "Jungle Potion");