INSERT INTO Quest(questName) VALUES("Animal Magnetism");
INSERT INTO Quest(questName) VALUES("Another Slice of H.A.M.");
INSERT INTO Quest(questName) VALUES("Between a Rock...");
INSERT INTO Quest(questName) VALUES("Big Chompy Bird Hunting");
INSERT INTO Quest(questName) VALUES("Biohazard");
INSERT INTO Quest(questName) VALUES("Black Knights' Fortress");
INSERT INTO Quest(questName) VALUES("Cabin Fever");
INSERT INTO Quest(questName) VALUES("Clock Tower");
INSERT INTO Quest(questName) VALUES("Cold War");
INSERT INTO Quest(questName) VALUES("Contact!");
INSERT INTO Quest(questName) VALUES("Cook's Assistant");
INSERT INTO Quest(questName) VALUES("Creature of Fenkenstrain");
INSERT INTO Quest(questName) VALUES("Darkness of Hallowvale");
INSERT INTO Quest(questName) VALUES("Death Plateau");
INSERT INTO Quest(questName) VALUES("Death to the Dorgeshuun");
INSERT INTO Quest(questName) VALUES("Demon Slayer");
INSERT INTO Quest(questName) VALUES("Desert Treasure");
INSERT INTO Quest(questName) VALUES("Devious Minds");
INSERT INTO Quest(questName) VALUES("The Digsite");
INSERT INTO Quest(questName) VALUES("Doric's Quest");
INSERT INTO Quest(questName) VALUES("Dragon Slayer");
INSERT INTO Quest(questName) VALUES("Dream Mentor");
INSERT INTO Quest(questName) VALUES("Druidic Ritual");
INSERT INTO Quest(questName) VALUES("Dwarf Cannon");
INSERT INTO Quest(questName) VALUES("Eadgar's Ruse");
INSERT INTO Quest(questName) VALUES("Eagle's Peak");
INSERT INTO Quest(questName) VALUES("Elemental Workshop I");
INSERT INTO Quest(questName) VALUES("Elemental Workshop II");
INSERT INTO Quest(questName) VALUES("Enakhra's Lament");
INSERT INTO Quest(questName) VALUES("Enlightened Journey");
INSERT INTO Quest(questName) VALUES("Ernest the Chicken");
INSERT INTO Quest(questName) VALUES("The Eyes of Glouphrie");
INSERT INTO Quest(questName) VALUES("Fairytale I - Growing Pains");
INSERT INTO Quest(questName) VALUES("Fairytale II - Cure a Queen");
INSERT INTO Quest(questName) VALUES("Family Quest");
INSERT INTO Quest(questName) VALUES("The Fued");
INSERT INTO Quest(questName) VALUES("Fight Arena");
INSERT INTO Quest(questName) VALUES("Fishing Contest");
INSERT INTO Quest(questName) VALUES("Forgettable Tale of a Drunken Dwarf");
INSERT INTO Quest(questName) VALUES("The Fremennik Isles");
INSERT INTO Quest(questName) VALUES("The Fremennik Trials");
INSERT INTO Quest(questName) VALUES("Garden of Tranquillity");
INSERT INTO Quest(questName) VALUES("Gertrude's Cat");
INSERT INTO Quest(questName) VALUES("Ghosts Ahoy");
INSERT INTO Quest(questName) VALUES("The Giant Dwarf");
INSERT INTO Quest(questName) VALUES("Goblin Diplomacy");
INSERT INTO Quest(questName) VALUES("The Golem");
INSERT INTO Quest(questName) VALUES("The Grand Tree");
INSERT INTO Quest(questName) VALUES("The Great Brain Robbery");
INSERT INTO Quest(questName) VALUES("Grim Tales");
INSERT INTO Quest(questName) VALUES("The Hand in the Sand");
INSERT INTO Quest(questName) VALUES("Haunted Mine");
INSERT INTO Quest(questName) VALUES("Hazeel Cult");
INSERT INTO Quest(questName) VALUES("Heroes' Quest");
INSERT INTO Quest(questName) VALUES("Holy Grail");
INSERT INTO Quest(questName) VALUES("Horror from the Deep");
INSERT INTO Quest(questName) VALUES("Icthlarin's Little Helper");
INSERT INTO Quest(questName) VALUES("Imp Catcher");
INSERT INTO Quest(questName) VALUES("In Aid of the Myreque");
INSERT INTO Quest(questName) VALUES("In Search of the Myreque");
INSERT INTO Quest(questName) VALUES("Jungle Potion");
INSERT INTO Quest(questName) VALUES("King's Ransom");
INSERT INTO Quest(questName) VALUES("The Knight's Sword");
INSERT INTO Quest(questName) VALUES("Legends' Quest");
INSERT INTO Quest(questName) VALUES("Lost City");
INSERT INTO Quest(questName) VALUES("The Lost Tribe");
INSERT INTO Quest(questName) VALUES("Lunar Diplomacy");
INSERT INTO Quest(questName) VALUES("Making History");
INSERT INTO Quest(questName) VALUES("Merlin's Crystal");
INSERT INTO Quest(questName) VALUES("Monkey Madness");
INSERT INTO Quest(questName) VALUES("Monkey Madness II");
INSERT INTO Quest(questName) VALUES("Monk's Friend");
INSERT INTO Quest(questName) VALUES("Mountain Daughter");
INSERT INTO Quest(questName) VALUES("Mourning's Ends Part I");
INSERT INTO Quest(questName) VALUES("Mourning's Ends Part II");
INSERT INTO Quest(questName) VALUES("Murder Mystery");
INSERT INTO Quest(questName) VALUES("My Arm's Big Adventure");
INSERT INTO Quest(questName) VALUES("Nature Spirit");
INSERT INTO Quest(questName) VALUES("Observatory Quest");
INSERT INTO Quest(questName) VALUES("Olaf's Quest");
INSERT INTO Quest(questName) VALUES("One Small Favour");
INSERT INTO Quest(questName) VALUES("Pirate's Treasure");
INSERT INTO Quest(questName) VALUES("Plague City");
INSERT INTO Quest(questName) VALUES("Priest in Peril");
INSERT INTO Quest(questName) VALUES("Prince Ali Rescue");
INSERT INTO Quest(questName) VALUES("Rag and Bone Man");
INSERT INTO Quest(questName) VALUES("Rat Catchers");
INSERT INTO Quest(questName) VALUES("Recipe for Disaster");
INSERT INTO Quest(questName) VALUES("Recruitment Drive");
INSERT INTO Quest(questName) VALUES("Regicide");
INSERT INTO Quest(questName) VALUES("The Restless Ghost");
INSERT INTO Quest(questName) VALUES("Romeo & Juliet");
INSERT INTO Quest(questName) VALUES("Roving Elves");
INSERT INTO Quest(questName) VALUES("Royal Trouble");
INSERT INTO Quest(questName) VALUES("Rum Deal");
INSERT INTO Quest(questName) VALUES("Rune Mysteries");
INSERT INTO Quest(questName) VALUES("Scorpion Catcher");
INSERT INTO Quest(questName) VALUES("Sea Slug");
INSERT INTO Quest(questName) VALUES("Shades of Mort'ton");
INSERT INTO Quest(questName) VALUES("Shadow of the Storm");
INSERT INTO Quest(questName) VALUES("Sheep Herder");
INSERT INTO Quest(questName) VALUES("Sheep Shearer");
INSERT INTO Quest(questName) VALUES("Shield of Arrav");
INSERT INTO Quest(questName) VALUES("Shilo Village");
INSERT INTO Quest(questName) VALUES("The Slug Menace");
INSERT INTO Quest(questName) VALUES("A Soul's Bane");
INSERT INTO Quest(questName) VALUES("Spirits of the Elid");
INSERT INTO Quest(questName) VALUES("Swan Song");
INSERT INTO Quest(questName) VALUES("Tai Bwo Wannai Trio");
INSERT INTO Quest(questName) VALUES("A Tail of Two Cats");
INSERT INTO Quest(questName) VALUES("Tears of Guthix");
INSERT INTO Quest(questName) VALUES("Temple of Ikov");
INSERT INTO Quest(questName) VALUES("Throne of Miscellania");
INSERT INTO Quest(questName) VALUES("The Tourist Trap");
INSERT INTO Quest(questName) VALUES("Tower of Life");
INSERT INTO Quest(questName) VALUES("Tree Gnome Village");
INSERT INTO Quest(questName) VALUES("Tribal Totem");
INSERT INTO Quest(questName) VALUES("Troll Romance");
INSERT INTO Quest(questName) VALUES("Troll Stronghold");
INSERT INTO Quest(questName) VALUES("Underground Pass");
INSERT INTO Quest(questName) VALUES("Vampire Slayer");
INSERT INTO Quest(questName) VALUES("Wanted!");
INSERT INTO Quest(questName) VALUES("Watchtower");
INSERT INTO Quest(questName) VALUES("Waterfall Quest");
INSERT INTO Quest(questName) VALUES("What Lies Below");
INSERT INTO Quest(questName) VALUES("Witch's House");
INSERT INTO Quest(questName) VALUES("Witch's Potion");
INSERT INTO Quest(questName) VALUES("Zogre Flesh Eaters");